import path from 'node:path';
import { visit, SKIP } from 'unist-util-visit';
import type { Root, InlineCode, Link } from 'mdast';
import { loadOrCreateApiSymbolManifest } from '../integrations/api-symbol-manifest';

const MANIFEST_PATH = path.resolve(import.meta.dirname, '..', '.api-symbol-manifest.json');
const API_REFERENCE_OUTPUT_DIR = path.resolve(import.meta.dirname, '..', 'src/content/docs/reference/api');

let cachedManifest: Record<string, string> | undefined;

/**
 * Loads the symbol manifest generated by the API reference integration.
 * @returns Map of symbol names to their API reference route paths.
 */
function loadManifest(): Record<string, string> {
  if (cachedManifest) return cachedManifest;

  const manifest = loadOrCreateApiSymbolManifest({
    outputDir: API_REFERENCE_OUTPUT_DIR,
    manifestPath: MANIFEST_PATH,
  });
  // Only cache non-empty manifests so we retry on the next page once the API reference is generated.
  if (Object.keys(manifest).length > 0) cachedManifest = manifest;
  return manifest;
}

/**
 * Canonicalizes manifest links to the lowercase routes generated by Starlight.
 * @param href - Manifest URL for an API symbol.
 * @returns Lowercase API reference route.
 */
function normalizeApiHref(href: string): string {
  return href.toLowerCase();
}

/**
 * Remark plugin that auto-links backtick code spans to their API reference
 * pages when a matching symbol exists in the generated manifest.
 *
 * For example, `AIAdapter` links to `/reference/api/ai-adapters-core/classes/aiadapter/`.
 *
 * Code spans already inside a link are left untouched. Only the first
 * occurrence per symbol per page is linked to avoid visual noise.
 * @returns Transformer that links API symbols in inline code spans.
 */
export function remarkAutoLinkApi(): (tree: Root) => void {
  return (tree: Root) => {
    const manifest = loadManifest();
    if (Object.keys(manifest).length === 0) return;

    const linked = new Set<string>();

    visit(tree, 'link', () => SKIP);

    visit(tree, 'inlineCode', (node: InlineCode, index, parent) => {
      if (index === undefined || !parent) return;
      if (parent.type === 'link') return;

      const symbol = node.value;
      if (linked.has(symbol)) return;

      const href = manifest[symbol];
      if (!href) return;

      linked.add(symbol);

      const link: Link = {
        type: 'link',
        url: normalizeApiHref(href),
        children: [{ type: 'inlineCode', value: symbol }],
      };
      parent.children[index] = link as (typeof parent.children)[number];
      return SKIP;
    });
  };
}
