import fs from 'node:fs';
import path from 'node:path';
import { visit, SKIP } from 'unist-util-visit';
import type { InlineCode, Link, Root, Text } from 'mdast';

const MANIFEST_PATH = path.resolve(import.meta.dirname, '..', '.package-route-manifest.json');

export interface RemarkAutoLinkPackagesOptions {
  /** Package specifier pattern owned by the website composition root. */
  readonly packageSpecifierPattern: RegExp;
  /** Exact package subpath links that should resolve to source instead of package pages. */
  readonly sourceOnlyLinks?: Readonly<Record<string, string>>;
}

let cachedManifest: Record<string, string> | undefined;

/**
 * Loads the package route manifest generated by the package pages integration.
 * @returns Map of package names to their generated website routes.
 */
function loadManifest(): Record<string, string> {
  if (cachedManifest) return cachedManifest;

  if (!fs.existsSync(MANIFEST_PATH)) return {};

  try {
    cachedManifest = JSON.parse(fs.readFileSync(MANIFEST_PATH, 'utf-8')) as Record<string, string>;
    return cachedManifest;
  } catch {
    return {};
  }
}

/**
 * Resolves a package specifier to its canonical website or source link.
 * @param specifier - Package name or package subpath.
 * @param manifest - Generated package route manifest.
 * @param options - Host-owned package matching and source-link policy.
 * @returns Link href for known package specifiers.
 */
function resolvePackageHref(
  specifier: string,
  manifest: Record<string, string>,
  options: RemarkAutoLinkPackagesOptions,
): string | undefined {
  if (!options.packageSpecifierPattern.test(specifier)) return undefined;

  const sourceOnlyHref = options.sourceOnlyLinks?.[specifier];
  if (sourceOnlyHref) return sourceOnlyHref;

  const [scope, name] = specifier.split('/');
  if (!scope || !name) return undefined;
  return manifest[`${scope}/${name}`];
}

/**
 * Reads the package specifier represented by a package Markdown link.
 * @param link - Markdown link node.
 * @param packageSpecifierPattern - Host-owned package specifier pattern.
 * @returns Package specifier when the link label is package-like.
 */
function packageSpecifierFromLink(link: Link, packageSpecifierPattern: RegExp): string | undefined {
  if (link.children.length !== 1) return undefined;

  const child = link.children[0] as InlineCode | Text | undefined;
  if (child?.type !== 'inlineCode' && child?.type !== 'text') return undefined;
  return packageSpecifierPattern.test(child.value) ? child.value : undefined;
}

/**
 * Remark plugin that links configured package specifiers to package docs or source.
 * @param options - Host-owned package matching and source-link policy.
 * @returns Transformer that links package specifiers in inline code spans and package-labelled links.
 */
export function remarkAutoLinkPackages(options: RemarkAutoLinkPackagesOptions): (tree: Root) => void {
  return (tree: Root) => {
    const manifest = loadManifest();
    const linked = new Set<string>();

    visit(tree, 'link', (node: Link) => {
      const specifier = packageSpecifierFromLink(node, options.packageSpecifierPattern);
      if (!specifier) return undefined;

      const href = resolvePackageHref(specifier, manifest, options);
      if (!href) return undefined;

      node.url = href;
      linked.add(specifier);
      return SKIP;
    });

    visit(tree, 'inlineCode', (node: InlineCode, index, parent) => {
      if (index === undefined || !parent) return;
      if (parent.type === 'link') return;

      const specifier = node.value;
      if (linked.has(specifier)) return;

      const href = resolvePackageHref(specifier, manifest, options);
      if (!href) return;

      linked.add(specifier);

      const link: Link = {
        type: 'link',
        url: href,
        children: [{ type: 'inlineCode', value: specifier }],
      };
      parent.children[index] = link as (typeof parent.children)[number];
      return SKIP;
    });
  };
}
