import { describe, expect, it } from 'bun:test';
import type { UserConfig } from 'vite';
import { CREATE_REQUIRE_BANNER, createSingleTargetAdapterConfig } from './vite.adapter.js';

/**
 * Read the configured Rollup banner from a generated Vite config.
 * @param config - Vite config generated by the adapter factory.
 * @returns String banner when one is configured.
 */
function getBanner(config: UserConfig): string | undefined {
  const build = typeof config.build === 'object' ? config.build : undefined;
  const output = build?.rollupOptions?.output;
  const firstOutput = Array.isArray(output) ? output[0] : output;
  return typeof firstOutput?.banner === 'string' ? firstOutput.banner : undefined;
}

describe('createSingleTargetAdapterConfig', () => {
  it('applies custom banners to browser adapter builds', () => {
    const config = createSingleTargetAdapterConfig('browser', {
      packageRoot: import.meta.dirname,
      banner: '// browser banner',
    });

    expect(getBanner(config)).toBe('// browser banner');
  });

  it('prepends createRequire before custom banners only for node adapter builds', () => {
    const config = createSingleTargetAdapterConfig('node', {
      packageRoot: import.meta.dirname,
      needsCreateRequire: true,
      banner: '// node banner',
    });

    expect(getBanner(config)).toBe(`${CREATE_REQUIRE_BANNER}\n// node banner`);
  });
});
