/**
 * Generation-leg descriptors for storage engines that ship as separate
 * packages.
 *
 * This table is the generation-time counterpart of the URL-scheme hint table
 * (`engine/hints.ts`): it is the only place this package keeps build-time
 * knowledge about engines it does not contain. The migration-tooling
 * orchestrator reads it to discover which non-baseline engines can contribute
 * a drizzle-kit generation leg, probing each engine's presence by package
 * resolution instead of hardwiring a specific engine workspace. The engine
 * package name, its drizzle-kit config path, and its post-generation normalize
 * script path are all data — this package never imports the engine package.
 *
 * The config and normalize specifiers are paths relative to the engine
 * package's root. The orchestrator resolves `'<enginePackageName>/package.json'`
 * to locate that root, then joins these paths against it. They are modeled as
 * relative paths (not module subpaths) because engine packages do not export
 * their drizzle-kit config or scripts as public subpath exports.
 * @packageDocumentation
 */
import type { StorageDialect } from '../types';

/**
 * One non-baseline engine's drizzle-kit generation leg.
 *
 * The baseline dialect (SQLite) has no entry here: its chain is generated by
 * the orchestrator directly. Every other dialect that can contribute a chain
 * declares its leg through this descriptor so the orchestrator stays free of
 * per-engine wiring.
 */
export interface StorageEngineGenerationLeg {
  /** Dialect this generation leg produces a migration chain for. */
  readonly dialect: StorageDialect;

  /** Package that provides the engine and its drizzle-kit generation assets. */
  readonly enginePackageName: string;

  /**
   * Name of the directory holding this engine's generated migration chain,
   * relative to the engine package root.
   */
  readonly chainDirName: string;

  /**
   * drizzle-kit config path for this engine, relative to the engine package
   * root. The orchestrator resolves the package root, then joins this path to
   * run `drizzle-kit generate --config <root>/<drizzleConfigSpecifier>`.
   */
  readonly drizzleConfigSpecifier: string;

  /**
   * Post-generation normalize script path for this engine, relative to the
   * engine package root. Optional: engines whose generated chains need no
   * normalization omit it.
   */
  readonly normalizeScriptSpecifier?: string;
}

/**
 * All non-baseline generation legs, in run order.
 *
 * Postgres: the engine lives in `@makaio/storage-pg`, its chain lands in
 * `drizzle-postgres`, drizzle-kit reads `drizzle.config.ts`, and the generated
 * SQL is normalized by `scripts/normalize-migrations.ts` — all relative to the
 * engine package root.
 */
export const NON_BASELINE_GENERATION_LEGS: readonly StorageEngineGenerationLeg[] = [
  {
    dialect: 'postgres',
    enginePackageName: '@makaio/storage-pg',
    chainDirName: 'drizzle-postgres',
    drizzleConfigSpecifier: 'drizzle.config.ts',
    normalizeScriptSpecifier: 'scripts/normalize-migrations.ts',
  },
];

/**
 * Find the generation leg for a dialect, if one exists.
 * @param dialect - Storage dialect to look up.
 * @returns The generation leg for the dialect, or `undefined` when the dialect
 *   has no non-baseline generation leg (the baseline dialect always returns
 *   `undefined`).
 */
export function findGenerationLegForDialect(dialect: StorageDialect): StorageEngineGenerationLeg | undefined {
  return NON_BASELINE_GENERATION_LEGS.find((leg) => leg.dialect === dialect);
}
