import { z } from 'zod';
import type { SchemaRecord } from '@makaio/core';
import { AgentRoleSchema } from './primitives.js';
import { MakaioSessionEventSchema } from './event.js';
import { ClientIdentityObservationSchema } from '../../client/account-identity.js';

/**
 * Session client-account linkage changed event payload.
 */
export const SessionClientAccountChangedSchema = z.object({
  sessionId: z.string().min(1),
  clientId: z.string().min(1),
  previousClientAccountId: z.string().min(1).nullable(),
  clientAccountId: z.string().min(1),
  source: z.string().min(1),
  observedAt: z.number().int().finite().nonnegative(),
  lastClientIdentityObservation: ClientIdentityObservationSchema,
});

export type SessionClientAccountChanged = z.infer<typeof SessionClientAccountChangedSchema>;

/**
 * Session event schemas.
 *
 * Handles session lifecycle events and context window state queries.
 */
export const EventSchemas = {
  /**
   * Agent added to session event.
   *
   * Subject: `session.agent.added`
   * Type: Event (fire-and-forget)
   * Emitted when: An agent is attached to a session
   * @example
   * ```typescript
   * bus.on(SessionSubjects.agent.added, (ctx) => {
   *   console.debug(`Agent ${ctx.payload.agentId} joined session ${ctx.payload.sessionId}`);
   * });
   * ```
   */
  'agent.added': z.object({
    /** Session the agent was added to */
    sessionId: z.string(),
    /** adapter's sessionId (generated by SDK / API) */
    adapterSessionId: z.string(),
    /** Unique agent execution unit ID */
    agentId: z.string(),
    /** Adapter instance that owns this agent */
    adapterId: z.string(),
    /** Adapter type name (e.g., 'claude-code', 'copilot') */
    adapterName: z.string(),
    /** Agent role. If omitted, first agent becomes 'lead', others 'member'. */
    role: AgentRoleSchema.optional(),
    /** Model identifier used by the agent (e.g., 'sonnet', 'opus') */
    model: z.string().optional(),
    /** Current working directory for the agent */
    cwd: z.string().optional(),
  }),

  /**
   * Agent removed from session event.
   *
   * Subject: `session.agent.removed`
   * Type: Event (fire-and-forget)
   * Emitted when: An agent is detached/removed from a session
   * @example
   * ```typescript
   * bus.on(SessionSubjects.agent.removed, (ctx) => {
   *   console.debug(`Agent ${ctx.payload.agentId} left session ${ctx.payload.sessionId}`);
   * });
   * ```
   */
  'agent.removed': z.object({
    /** Session the agent was removed from */
    sessionId: z.string(),
    /** Unique agent execution unit ID */
    agentId: z.string(),
  }),

  /**
   * Session closed event.
   *
   * Subject: `session.closed`
   * Type: Event (fire-and-forget)
   * Emitted when: A session is closed (via close request)
   * @example
   * ```typescript
   * bus.on(SessionSubjects.closed, (ctx) => {
   *   console.debug(`Session ${ctx.payload.sessionId} closed`);
   *   if (ctx.payload.reason) {
   *     console.debug(`Reason: ${ctx.payload.reason}`);
   *   }
   * });
   * ```
   */
  closed: z.object({
    /** ID of the closed session */
    sessionId: z.string(),
    /** Optional reason for closure */
    reason: z.string().optional(),
  }),

  /**
   * Session resumed event.
   *
   * Subject: `session.resumed`
   * Type: Event (fire-and-forget)
   * Emitted when: A closed session is resumed to active state
   */
  resumed: z.object({
    /** ID of the resumed session */
    sessionId: z.string(),
  }),

  /**
   * Session archived event.
   *
   * Subject: `session.archived`
   * Type: Event (fire-and-forget)
   * Emitted when: A closed session is archived
   */
  archived: z.object({
    /** ID of the archived session */
    sessionId: z.string(),
  }),

  /**
   * Session purged event.
   *
   * Subject: `session.purged`
   * Type: Event (fire-and-forget)
   * Emitted when: A session is permanently deleted (via purge request)
   * @example
   * ```typescript
   * bus.on(SessionSubjects.purged, (ctx) => {
   *   console.debug(`Session ${ctx.payload.sessionId} purged`);
   * });
   * ```
   */
  purged: z.object({
    /** ID of the purged session */
    sessionId: z.string(),
  }),

  /**
   * Session compressed event.
   *
   * Subject: `session.compressed`
   * Type: Event (fire-and-forget)
   * Emitted when: A session's context is compressed (via compress request)
   *
   * Used to notify components (like ContextWindowTracker) that context state
   * should be cleared since compression resets the context window.
   * @example
   * ```typescript
   * bus.on(SessionSubjects.compressed, (ctx) => {
   *   console.debug(`Session ${ctx.payload.sessionId} compressed`);
   *   // Clear cached context state
   * });
   * ```
   */
  compressed: z.object({
    /** ID of the compressed session */
    sessionId: z.string(),
    /** Event ID of the squash event created */
    eventId: z.string(),
  }),

  /**
   * Session client-account linkage changed event.
   *
   * Subject: `session.clientAccount.changed`
   * Type: Event (fire-and-forget)
   * Emitted when: A session resolves to a different canonical client account
   */
  'clientAccount.changed': SessionClientAccountChangedSchema,

  /**
   * Request UI to open history editing flow after a connector swap decision.
   *
   * Subject: `session.connectorSwap.editRequested`
   * Type: Event (fire-and-forget)
   */
  'connectorSwap.editRequested': z.object({
    /** Session containing the affected agent */
    sessionId: z.string(),
    /** Agent that triggered connector swap flow */
    agentId: z.string(),
    /** Previous working directory (for cwd swaps) */
    previousCwd: z.string().optional(),
    /** New working directory (for cwd swaps) */
    newCwd: z.string().optional(),
    /** Previous model (for model swaps) */
    previousModel: z.string().optional(),
    /** New model (for model swaps) */
    newModel: z.string().optional(),
  }),

  /**
   * Get context window state for a session.
   *
   * Subject: `session.getContextWindowState`
   * Type: Request (RPC)
   *
   * Returns the current context window usage for a session, aggregated
   * across all agents (using "worst agent" strategy).
   * @example
   * ```typescript
   * const { state } = await bus.request(SessionSubjects.getContextWindowState, {
   *   sessionId: 'session-123',
   * });
   * if (state.level === 'critical') {
   *   // Suggest compression
   * }
   * ```
   */
  getContextWindowState: {
    request: z.object({
      /** Session ID to get context state for */
      sessionId: z.string(),
    }),
    response: z.object({
      /** Context window state (null if no data available) */
      state: z
        .object({
          currentTokens: z.number(),
          maxTokens: z.number(),
          percentage: z.number(),
          level: z.enum(['ok', 'warn', 'critical']),
          /** Timestamp of the last agent update that produced this state */
          lastUpdatedAt: z.number(),
        })
        .nullable(),
    }),
  },

  /**
   * Catch-all session event for observability and persistence.
   *
   * Subject: `session.event`
   * Type: Event (fire-and-forget)
   * Use for: Single subscription to all session events, event storage
   */
  event: MakaioSessionEventSchema,
} satisfies SchemaRecord;
