/**
 * Subject telemetry bus schemas.
 *
 * Defines Zod schemas for sanitized bus subject telemetry facts emitted by
 * the projection layer, plus the bus schema record that marks telemetry facts
 * as collector-only. Import this module when you only need types or validation
 * shapes without registering the namespace on the bus. To register the
 * namespace, import `./namespace` instead.
 * @packageDocumentation
 */

import { z } from 'zod';
import { collectorOnlySubject, type SchemaRecord } from '@makaio/core';

/**
 * Scalar attribute value allowed in a telemetry fact.
 *
 * Restricted to primitives and homogeneous primitive arrays so that the
 * telemetry sink can safely serialize without inspecting arbitrary objects.
 */
export const SubjectTelemetryAttributeValueSchema = z.union([
  z.string(),
  z.number(),
  z.boolean(),
  z.null(),
  z.array(z.string()),
  z.array(z.number()),
  z.array(z.boolean()),
  z.array(z.null()),
]);

/** Inferred TypeScript type for a sanitized attribute value. */
export type SubjectTelemetryAttributeValue = z.infer<typeof SubjectTelemetryAttributeValueSchema>;

/**
 * Bus message kind projected into a telemetry fact.
 * Covers local bus API entrypoints observed by this MVP.
 */
export const SubjectTelemetryMessageTypeSchema = z.enum(['event', 'request', 'broadcast']);

/**
 * Flow direction of the observed message at the source runtime.
 *
 * - `local` — originated and consumed within the same runtime.
 * - `outbound` — dispatched to a remote peer.
 * - `inbound` — received from a remote peer.
 */
export const SubjectTelemetryDirectionSchema = z.enum(['local', 'outbound', 'inbound']);

/**
 * Sanitized bus subject telemetry fact schema.
 *
 * A fact captures the observable, non-sensitive metadata of a single bus
 * message. All payload content is excluded; only correlation handles and
 * namespace-approved scalar attributes are present.
 */
export const SubjectTelemetryFactSchema = z
  .object({
    /** Stable fact identifier generated by the projection layer. */
    factId: z.string().min(1),
    /** Wall-clock timestamp in Unix milliseconds. */
    observedAt: z.number().int().nonnegative(),
    /** Source runtime machine identifier. */
    machineId: z.string().min(1).optional(),
    /** Full bus namespace that owns the observed subject. */
    namespace: z.string().min(1),
    /** Full bus subject key. */
    subject: z.string().min(1),
    /** Bus message kind projected into this fact. */
    messageType: SubjectTelemetryMessageTypeSchema,
    /** Direction at the source runtime. */
    direction: SubjectTelemetryDirectionSchema,
    /** Raw bus message id. Safe to expose as a correlation handle, not as payload. */
    messageId: z.string().min(1),
    /** Raw bus correlation id when the source message has one. */
    correlationId: z.string().min(1).optional(),
    /** Sanitized scalar attributes approved by namespace-owned policy. */
    attributes: z.record(z.string(), SubjectTelemetryAttributeValueSchema),
  })
  .strict();

/** Inferred TypeScript type for a sanitized bus subject telemetry fact. */
export type SubjectTelemetryFact = z.infer<typeof SubjectTelemetryFactSchema>;

/**
 * Subject telemetry domain bus schemas aggregate.
 *
 * Each key becomes a subject identifier as `subject-telemetry.<key>`.
 */
export const SubjectTelemetrySchemas = {
  /**
   * A single sanitized telemetry fact emitted by the projection layer.
   * Event: transport-ingestable by collectors, never laterally relayed.
   */
  fact: collectorOnlySubject(SubjectTelemetryFactSchema),
} satisfies SchemaRecord;
