/* eslint-disable max-lines */
export { AIModelSchema, AIReasoningLevelSchema, ProviderAIModelSchema } from './model/index.js';
export type {
  AIModel,
  AIModelMetadata,
  AIReasoningLevel,
  DiscoveredAIModel,
  ProviderAIModel,
  ReasoningLevelMap,
  STTCapability,
  TTSCapability,
} from './model/index.js';
export {
  ModelFilterModeSchema,
  ModelVisibilitySchema,
  ProtocolEndpointsSchema,
  ProtocolIdSchema,
  ProviderDefinitionSchema,
  resolveModelVisibility,
} from './provider/index.js';
export type {
  ModelFilterMode,
  ModelVisibility,
  ProtocolEndpoints,
  ProtocolId,
  ProviderDefinition,
  ProviderDefinitionInput,
} from './provider/index.js';
export {
  AdapterNamespace,
  AdapterSessionStatusSchema,
  AdapterSubjects,
  AgentSelectionBaseSchema,
  AgentSelectionSchema,
  COMPRESS_SESSION_LINEAGE_KIND,
  CompressSessionLineageSchema,
  FORK_SESSION_LINEAGE_KIND,
  ForkSessionLineageSchema,
  ProviderContextSchema,
  ROOT_SESSION_LINEAGE_KIND,
  RootSessionLineageSchema,
  SESSION_LINEAGE_KINDS,
  SessionDiscoveredSchema,
  SessionLineageKindSchema,
  SUBAGENT_SESSION_LINEAGE_KIND,
  SubagentSessionLineageSchema,
} from './adapter/index.js';
export type {
  AdapterRuntimeOptions,
  AdapterSelection,
  AdapterSessionStatus,
  AgentSelection,
  AgentSelectionBase,
  AgentSelectionKindMap,
  ProviderContext,
  SessionDiscovered,
  SessionLineage,
  SessionLineageKind,
  SessionLinked,
  StartAgentRequest,
  StartAgentResponse,
} from './adapter/index.js';
export {
  CanonicalModelSubjects,
  isCanonicalModelParseError,
  parseCanonicalModel,
  VIRTUAL_NAME_RE,
} from './canonical-model/index.js';
export type {
  CanonicalModelResolvedSelection,
  CanonicalModelSelection,
  ResolvableCanonicalModel,
} from './canonical-model/index.js';
export { AgentNamespace, AgentSchemas, AgentSubjects, AgentToolApproveSchema, StepTypeSchema } from './agent/index.js';
export type {
  AgentComplete,
  AgentMessage,
  AgentStarted,
  AgentToolApproveRequest,
  AgentToolApproveResponse,
  BlockData,
  SendMessageRequest,
  SendMessageResponse,
  SessionMetadata,
  StepFinished,
  StepStarted,
  StepType,
  ToolCompleted,
  ToolStarted,
} from './agent/index.js';
export { AgentResolutionSubjects, ResolvedAgentConfigSchema } from './agent-resolution/index.js';
export type { AgentResolutionContext, ResolvedAgentConfig } from './agent-resolution/index.js';
export { ApprovalNamespace, ApprovalSubjects } from './approval/index.js';
export type {
  ApprovalEntry,
  ResolvedApprovalEntry,
  ResolveEnrichedPolicyResponse,
  RiskLevel,
} from './approval/index.js';
export {
  AUTO_LAUNCH_CAPABILITY_ID,
  FindingOriginSchema,
  FindingSeveritySchema,
  FindingStatusSchema,
  FindingTargetSchema,
  registerAutoLaunchProvider,
  registerReviewerProcessor,
  registerReviewSource,
  registerVCSProvider,
  unregisterReviewerProcessor,
  unregisterReviewSource,
  unregisterVCSProvider,
  REVIEW_SOURCE_CAPABILITY_ID,
  REVIEWER_PROCESSOR_CAPABILITY_ID,
  ReviewFindingSchema,
  ReviewIssueCommentSchema,
  ReviewNamespace,
  ReviewSchemas,
  ReviewSourceRateLimitSchema,
  ReviewSubjects,
  STT_MODE_LITERALS,
  SuggestedChangeSchema,
  TTS_MODE_LITERALS,
  VCS_CAPABILITY_ID,
  VCSCommitStatusSchema,
  VCSEvents,
  VCSSubjects,
  VisionNamespace,
  VisionSchemas,
  VisionSubjects,
  VoiceProviderPreferenceSchema,
  VoiceSubjects,
  CheckRunDetailSchema,
  ChecksSummarySchema,
  FindingsSummarySchema,
  LabelInfoSchema,
  LabelSemanticSchema,
  PullRequestStateSchema,
  ReadinessAssessmentSchema,
  ReviewerStateSchema,
  ReviewsSummarySchema,
  VCSPRNamespace,
  VCSPRSchemas,
  VCSPRSubjects,
} from './capabilities/index.js';
export type {
  AudioChunk,
  ClientVoiceProviderDescriptor,
  FetchFindingsParams,
  FindingOrigin,
  FindingSeverity,
  FindingStatus,
  FindingTarget,
  IAutoLaunchProvider,
  IReviewerProcessor,
  IReviewSource,
  ISTTProvider,
  ITTSProvider,
  IVCSProvider,
  IVisionProvider,
  IVocabularyProvider,
  ProcessCliOutputParams,
  ProcessCommentsParams,
  ProcessIssueCommentsParams,
  ProcessReviewBodyParams,
  ProviderRuntime,
  ReviewFinding,
  ReviewIssueComment,
  ReviewRequestContext,
  ReviewSourceRateLimit,
  ReviewSourceSnapshot,
  ReviewTriggerParams,
  ReviewTriggerResult,
  STTMode,
  STTProviderCapabilities,
  STTRequest,
  STTResult,
  SuggestedChange,
  TTSMode,
  TTSProviderCapabilities,
  TTSRequest,
  VCSCheckRun,
  VCSCommitStatus,
  VCSPullRequest,
  VCSPullRequestDetail,
  VCSRepository,
  VCSReview,
  VCSReviewComment,
  VisionAnalysisRequest,
  VisionAnalysisResult,
  VoicePipelineLeg,
  VoicePipelineStrategy,
  VoiceProviderPreference,
  VoiceSessionStartResponse,
  VoiceStatusState,
  CheckRunDetail,
  ChecksSummary,
  FindingsSummary,
  LabelInfo,
  LabelSemantic,
  PullRequestState,
  ReadinessAssessment,
  ReviewerState,
  ReviewsSummary,
} from './capabilities/index.js';
export { CapabilitySubjects } from './capability/index.js';
export type {
  ICapabilityBasedService,
  ICapabilityProvider,
  ProviderRegistration,
  ProviderSummary,
  ProviderUnregistration,
} from './capability/index.js';
export {
  ApprovalPolicySchema,
  codexCapabilityMap,
  DEFAULT_HARNESSES,
  expandCapabilities,
  expandProfileToolCapabilities,
  HarnessDefinitionBaseSchema,
  HarnessDefinitionCreateSchema,
  HarnessDefinitionSchema,
  HarnessSubjects,
} from './harness/index.js';
export type {
  ApprovalPolicy,
  HarnessDefinition,
  HarnessDefinitionCreate,
  ProfileToolCapabilitiesConfig,
} from './harness/index.js';
export { HostNamespace, HostSchemas, HostSubjects, WindowStateSchema } from './host/index.js';
export type {
  TrayActivateRequest,
  TrayActivateResponse,
  WindowClosedEvent,
  WindowCreateRequest,
  WindowCreateResponse,
  WindowFocusRequest,
  WindowFocusResponse,
  WindowLabelChangedEvent,
  WindowListRequest,
  WindowListResponse,
  WindowOpenedEvent,
  WindowState,
} from './host/index.js';
export { PlatformNamespace, PlatformSchemas, PlatformSubjects } from './platform/index.js';
export type {
  AutoLaunchDisableResponse,
  AutoLaunchEnableRequest,
  AutoLaunchEnableResponse,
  AutoLaunchStatusResponse,
} from './platform/index.js';
export {
  MCP_CALL_TOOL_NAME,
  MCP_DISCOVER_TOOL_NAME,
  MCP_SCHEMA_TOOL_NAME,
  McpAutoReconnectConfigSchema,
  McpExposureModeSchema,
  McpNonHiddenExposureModeSchema,
  McpProfileConfigSchema,
  McpSubjects,
  McpToolPatternSchema,
  McpTransportConfigSchema,
} from './mcp/index.js';
export type {
  McpAgentContext,
  McpAutoReconnectConfig,
  McpExposureMode,
  McpProfileConfig,
  McpResolvedServer,
  McpSessionContext,
  McpToolState,
  McpTransportConfig,
} from './mcp/index.js';
export {
  AgentStatusSchema,
  compareMessageCursorAsc,
  compareMessageCursorDesc,
  CompressionModeSchema,
  CONNECTOR_SWAP_CANCELLED_CODE,
  CONNECTOR_SWAP_WARNING_OPTION_IDS,
  CONNECTOR_SWAP_WARNING_SUPPRESSED_KEY,
  ConnectorSwapCancelledError,
  ForkTransformsSchema,
  INTERACTIVE_DIALOG_TIMEOUT_MS,
  isConnectorSwapCancelledError,
  isInViewBranch,
  isKnownSessionEvent,
  MakaioSessionAgentSchema,
  MakaioSessionEventSchema,
  MakaioSessionSchema,
  messageCursorKey,
  MessagePageCursorSchema,
  MessageRoutingSchema,
  MessageStorageNamespace,
  MessageStorageSubjects,
  messageToCursor,
  safeValidateSnapshot,
  SESSION_EVENT_TYPES,
  SessionContextSchema,
  SessionEventStorageNamespace,
  SessionEventStorageSubjects,
  SessionMessageSchema,
  SessionPreviewDataSchema,
  SessionSnapshotSchema,
  SessionStorageNamespace,
  SessionStorageSetRequestSchema,
  SessionStorageSetSessionSchema,
  SessionStorageSubjects,
  SessionStorageUpdateSchema,
  SessionNamespace,
  SessionSubjects,
  SessionWithPreviewSchema,
  SNAPSHOT_VERSION,
  TurnSchema,
  TurnStatusSchema,
  TurnUsageSchema,
  UI_WARNINGS_CATEGORY,
  validateSnapshot,
} from './session/index.js';
export type {
  AgentRole,
  BranchKind,
  CompressionMode,
  ContextWindowState,
  ForkChildInfo,
  ForkOptions,
  ForkTransforms,
  IMakaioSession,
  MakaioSessionAgent,
  MakaioSessionEvent,
  MessagePageCursor,
  MessageRouting,
  MessageRoutingStatus,
  ResolveAgentConfigResponse,
  SegmentPolicy,
  SessionContext,
  SessionCreated,
  SessionEventPayload,
  SessionEventType,
  SessionEventTypeMap,
  SessionExtensionContext,
  SessionMessage,
  SessionMessageBlock,
  SessionMessageOrigin,
  SessionPreviewData,
  SessionSendMessageRequest,
  SessionSnapshot,
  SessionUpdatedEvent,
  SessionWithPreview,
  SnapshotExportOptions,
  SnapshotImportConflictErrorData,
  SnapshotPreviewData,
  Turn,
  TurnInitiator,
  TurnStatus,
  TurnUsage,
  UsageMetrics,
} from './session/index.js';
export { EntityUIConfigSchema, ERROR_CATEGORIES, ErrorCategorySchema, JsonValueSchema } from './shared/index.js';
export type {
  ContentSource,
  CustomFieldDefinition,
  EntityUIConfig,
  ErrorCategory,
  FieldDefinition,
  FieldOption,
  FieldType,
  FieldWidget,
  FormFieldProps,
  JsonValue,
  Message,
  MessageBlock,
  MessageDeliveryMode,
  MessageInput,
  MessageOutcome,
  SendMessageResultInnerResult,
  StandardFieldDefinition,
  SystemPrompt,
} from './shared/index.js';
export {
  SkillActivationTriggerSchema,
  SkillDeactivationReasonSchema,
  SkillFrontmatterSchema,
  SkillNamespace,
  SkillRecordInputSchema,
  SkillRuntimePolicySchema,
  SkillStorageNamespace,
  SkillStorageSubjects,
  SkillSubjects,
  validateSkillScope,
} from './skill/index.js';
export type {
  ActivatedSkillMetadata,
  ActiveSkillState,
  SkillActivateRequest,
  SkillActivateResponse,
  SkillActivationMode,
  SkillActivationTrigger,
  SkillCatalogEntry,
  SkillCatalogTurnEntry,
  SkillDeactivationReason,
  SkillFrontmatter,
  SkillGetActiveSkillsRequest,
  SkillGetActiveSkillsResponse,
  SkillGetCatalogRequest,
  SkillGetCatalogResponse,
  SkillQuery,
  SkillRecord,
  SkillRecordInput,
  SkillReinjection,
  SkillRuntimePolicy,
  SkillScope,
  SkillSource,
  SkillTurnEntry,
} from './skill/index.js';
export type { ActionIntent, FocusContext, SurfaceType } from './common/index.js';
export {
  ContextModeSchema,
  DEFAULT_CONSTRAINTS,
  PendingRequestSchema,
  SpawnSubagentRpcRequestSchema,
  SubagentConfigSchema,
  SubagentError,
  SubagentErrorCode,
  SubagentStatusSchema,
  SubagentSubjects,
} from './subagent/index.js';
export type {
  AwaitSubagentRequest,
  AwaitSubagentResponse,
  CompleteTaskRequest,
  CompleteTaskResponse,
  ContextMode,
  ExecuteSubagentResponse,
  KillSubagentRequest,
  KillSubagentResponse,
  ListSubagentsBySessionRequest,
  ListSubagentsBySessionResponse,
  PendingRequest,
  ReportProgressRequest,
  ReportProgressResponse,
  RequestInputRpcRequest,
  RequestInputRpcResponse,
  SendToSubagentRequest,
  SendToSubagentResponse,
  SpawnSubagentRpcRequest,
  SpawnSubagentRpcResponse,
  SubagentConfig,
  SubagentConstraints,
  SubagentExecutionFailed,
  SubagentStatus,
} from './subagent/index.js';
export { ToolNamespace, ToolSubjects, validateToolAdapterIdentity } from './tool/index.js';
export type {
  ToolAdapterIdentity,
  ToolAnnotations,
  ToolExecuteResult,
  ToolExecutionContextOverrides,
  ToolListItem,
} from './tool/index.js';
export { computeMetaTags, ToolCapability, ToolCapabilitySchema } from './tool-capability/index.js';
export type { CapabilityGroup, CapabilityItem, CapabilityPickerValue, ToolMetaTag } from './tool-capability/index.js';
export { MakaioVariantSchema, VariantNamespace, VariantSubjects, VariantUpgradeStatusSchema } from './variant/index.js';
export type {
  MakaioVariant,
  VariantGetInfoResponse,
  VariantRequestUpgradeRequest,
  VariantRequestUpgradeResponse,
  VariantUpgradeProgressEvent,
  VariantUpgradeStatus,
} from './variant/index.js';
export {
  ExecutionListQuerySchema,
  WorkflowDefinitionInputSchemaTyped,
  WorkflowDefinitionSchemaTyped,
  WorkflowExecutionSchema,
  WorkflowListQuerySchema,
} from './workflow/index.js';
export type {
  AgentWorkflowStep,
  ForEachWorkflowStep,
  IWorkflowTriggerTypeRegistry,
  ShellWorkflowStep,
  StepState,
  StepStatus,
  WorkflowDefinition,
  WorkflowDefinitionInput,
  WorkflowExecution,
  WorkflowInput,
  WorkflowStep,
  WorkflowTrigger,
  WorkflowTriggerTypeRecord,
} from './workflow/index.js';
export {
  BrowserEntrypointSchema,
  CliManifestSchema,
  ExtensionDescriptorSchema,
  extensionToken,
  ExtensionWarningEntrySchema,
  ExtensionWarningSchema,
  getBootstrapAssetKey,
  getExtensionWarningActionLabel,
  parseExtensionConfig,
} from './extension/index.js';
export type {
  ActionCategory,
  ActionCategoryMap,
  ActionShortcut,
  ActionShortcutModifiers,
  AdapterClientRef,
  AdapterContribution,
  AdapterDefinitionContract,
  AdapterProviderDefinitionContract,
  AdapterProviderRef,
  BootstrapAsset,
  BootstrapAssetKey,
  BootstrapChoice,
  BootstrapDiscoverContext,
  BootstrapExportContext,
  BootstrapExportResult,
  BootstrapImportContext,
  BootstrapImportResult,
  BootstrapResult,
  CapabilityToken,
  CliArgManifest,
  CliManifest,
  CliSubcommandManifest,
  CreateSessionEventActionResult,
  EntrypointConfig,
  EventFilter,
  ExecuteContext,
  ExecuteResult,
  ExtensionBootstrap,
  ExtensionConfigComponentProps,
  ExtensionConfigProvider,
  ExtensionContext,
  ExtensionContributionProcessor,
  ExtensionDescriptor,
  ExtensionEntrypoints,
  ExtensionFieldTypeLoader,
  ExtensionIdentity,
  ExtensionService,
  ExtensionServiceLifecycle,
  ExtensionToken,
  ExtensionWarning,
  ExtensionWarningAction,
  ExtensionWarningEntry,
  HashTrigger,
  HashTriggerContext,
  HashTriggerMetadata,
  HashTriggerSuggestResult,
  LoaderContext,
  MakaioExtension,
  MakaioWebUiActions,
  MakaioWebUiComponentProps,
  MakaioWebUiRoute,
  MessageEventFilter,
  MessageRole,
  NodeExtensionContext,
  PageComponentProps,
  PageDeclaration,
  PickerConfig,
  PickerOpenContext,
  SelectionChangeContext,
  SelectionFeedback,
  SessionEventActionContext,
  SessionEventActionDeclaration,
  SessionEventActionOptions,
  StructuralEventFilter,
  TileDeclaration,
  TileProps,
  ToolCallFormatterDeclaration,
  TrayManifest,
  UiContextDimension,
  UiContextSnapshot,
  UiContextValueMap,
  UiNavigationLevel,
  UiNavigationLevelMap,
  UiRuntimeNavigationLevel,
  UiScope,
  UiScopeMap,
  WhenContext,
  WidgetDeclaration,
  WidgetProps,
  WindowParamSpec,
} from './extension/index.js';
export { CredentialSubjects } from './credential/index.js';
export {
  ClientAccountIdentifierSchema,
  ClientDefinitionSchema,
  ClientIdentityObservationSchema,
  ClientSessionAccountObserveSchema,
  ClientSubjects,
  ClientToolDefinitionSchema,
  ClientWiringEntrySchema,
  createClientDefinition,
  LatestVersionSourceStatusSchema,
  LogSourceDefinitionSchema,
  ManagedInstallDescriptorSchema,
} from './client/index.js';
export type {
  ClientAccountIdentifier,
  ClientAccountObserveRequest,
  ClientBinaryListEntry,
  ClientDefinition,
  ClientExecutionContext,
  ClientIdentityObservation,
  ClientInstallCompleted,
  ClientInstallProgress,
  ClientRuntimeObserveRequest,
  ClientRuntimeStarted,
  ClientScanResult,
  ClientScanTarget,
  ClientSessionAccountObserveRequest,
  ClientSessionAccountObserveResponse,
  ClientSessionLocator,
  ClientSessionObservedBase,
  ClientSessionStarted,
  ClientSessionToolPost,
  ClientSessionToolPre,
  ClientSessionTurnCompleted,
  ClientSessionUserPromptSubmitted,
  ClientToolDefinition,
  ClientUsageIngestRequest,
  ClientUsageSnapshot,
  ClientUsageWindow,
  ClientVersionChanged,
  ClientWiringEntry,
  GithubReleaseInstallDescriptor,
  InstalledVersionEntry,
  InstallStage,
  LatestVersionSourceStatus,
  LogSourceDefinition,
  ManagedInstallDescriptor,
  ManagedInstallStrategy,
  ManifestBucketInstallDescriptor,
  NpmInstallDescriptor,
  PostInstallDescriptor,
} from './client/index.js';
export { NativeSessionSupervisorSubjects, SupervisorSessionStatusSchema } from './native-session-supervisor/index.js';
export type {
  NativeSupervisorAttachRequest,
  NativeSupervisorLaunchRequest,
  NativeSupervisorStatusRequest,
  NativeSupervisorStopRequest,
  SupervisorRuntimeSnapshot,
  SupervisorSessionStatus,
} from './native-session-supervisor/index.js';
export { ConfigSchema } from './config/config-schema.js';
export type { Config, RelayConfig } from './config/config-schema.js';
export { ConfigSchemas } from './config/config-subjects.js';
export type { ConfigGetResponse, ConfigUpdateRequest, ConfigUpdateResponse } from './config/config-subjects.js';
export { ConfigSubjects } from './config/config-namespace.js';
// Toast schemas and namespace registration are available via the
// '@makaio/contracts/toast' subpath import. Excluded from the root
// barrel to avoid adding another namespace registration side effect
// — the root barrel already pulls in some (config, session) but we
// are not making that worse.
