/**
 * `@makaio/services-core/git/schemas`
 *
 * Pure git-service Zod schemas and TypeScript types.
 * No service dependencies — safe for type-only consumers.
 */
export {
  GitFileChangeSchema,
  GitChangeStatsSchema,
  GitCommitDetailsResponseSchema,
  GitWorkingTreeFileChangeSchema,
  GitWorkingTreeDetailsResponseSchema,
  GitWorkingTreeDetailsRequestSchema,
  GitWorktreeInfoSchema,
  GitWorktreesResponseSchema,
  GitLogCommitSchema,
  GitRefsSchema,
  GitStatusResponseSchema,
  GitStatusRequestSchema,
  GitBranchResponseSchema,
  GitBranchRequestSchema,
  GitRemoteSchema,
  GitRemotesResponseSchema,
  GitDefaultBranchResponseSchema,
  GitLogFiltersSchema,
  GitLogRequestSchema,
  GitLogResponseSchema,
  GitFileAtRevisionRequestSchema,
  GitFileAtRevisionResponseSchema,
  GitBlobHashAtCommitResponseSchema,
  GitWorktreesRequestSchema,
  GitFingerprintRequestSchema,
  GitFingerprintResponseSchema,
  GitCommitRequestSchema,
  GitCommitResponseSchema,
} from '@makaio/services-core/git/schemas';
export type {
  GitFileChange,
  GitChangeStats,
  GitCommitDetailsResponse,
  GitWorkingTreeFileChange,
  GitWorkingTreeDetailsResponse,
  GitWorkingTreeDetailsRequest,
  GitWorktreeInfo,
  GitWorktreesResponse,
  GitLogCommit,
  GitRefs,
  GitStatusResponse,
  GitBranchResponse,
  GitBranchRequest,
  GitRemote,
  GitRemotesResponse,
  GitBlameResponse,
  GitBlameLine,
  GitFileAtRevisionResponse,
  GitFileAtRevisionRequest,
  GitFileAtCommitResponse,
  GitBlobHashAtCommitResponse,
  GitDiffResponse,
  GitLogFilters,
  GitLogRequest,
  GitLogResponse,
  GitRepoRootResponse,
  GitDefaultBranchResponse,
  GitCommitResponse,
  GitFingerprintRequest,
  GitFingerprintResponse,
} from '@makaio/services-core/git/schemas';
export {
  GitCommitEventSchema,
  GitCheckoutEventSchema,
  GitStagingEventSchema,
  GitMergeEventSchema,
  GitRebaseStatusSchema,
  GitRebaseEventSchema,
  GitWorktreeEventSchema,
  GitAddRepoRequestSchema,
  GitAddRepoResponseSchema,
  GitRemoveRepoRequestSchema,
  GitRemoveRepoResponseSchema,
  GitInitRepoRequestSchema,
  GitInitRepoResponseSchema,
  GitCreateWorktreeRequestSchema,
  GitCreateWorktreeResponseSchema,
  GitRemoveWorktreeRequestSchema,
  GitRemoveWorktreeResponseSchema,
  GitStageRequestSchema,
  GitStageResponseSchema,
  GitUnstageRequestSchema,
  GitUnstageResponseSchema,
} from '@makaio/services-core/git/schemas';
export type {
  GitCommitEvent,
  GitCheckoutEvent,
  GitStagingEvent,
  GitMergeEvent,
  GitRebaseStatus,
  GitRebaseEvent,
  GitWorktreeEvent,
  GitStageResponse,
  GitUnstageResponse,
  GitAddRepoRequest,
  GitAddRepoResponse,
  GitRemoveRepoRequest,
  GitRemoveRepoResponse,
  GitInitRepoRequest,
  GitInitRepoResponse,
  GitCreateWorktreeRequest,
  GitCreateWorktreeResponse,
  GitRemoveWorktreeRequest,
  GitRemoveWorktreeResponse,
  GitStageRequest,
  GitUnstageRequest,
} from '@makaio/services-core/git/schemas';
export type {
  ICommitMessageStrategy,
  CommitMessageContext,
  CommitMessageResult,
  CommitMessageStrategyId,
  MergeContext,
  MergeStrategyId,
  IMergeHook,
  IMergeStrategy,
} from '@makaio/services-core/git/schemas';
export { CommitMessageStrategyIdSchema, MergeStrategyIdSchema } from '@makaio/services-core/git/schemas';
