export {
  ArtifactActorSchema,
  ArtifactCompareRequestSchema,
  ArtifactCompareResponseSchema,
  ArtifactConflictPolicySchema,
  ArtifactKindRegistrationSchema,
  ArtifactObservationSchema,
  ArtifactQueryRequestSchema,
  ArtifactQueryScopeSchema,
  ArtifactRefSchema,
  ArtifactRelationQueryTargetSchema,
  ArtifactRelationSchema,
  ArtifactRelationTargetSchema,
  ArtifactRepresentationsSchema,
  ArtifactRevisionSchema,
  ArtifactScopeSchema,
  ConfidenceBasisSchema,
  ConfidenceLevelSchema,
  ConfidenceMetadataSchema,
  EvidenceRefSchema,
  LocalRefSchema,
  RelationTypeRegistrationSchema,
} from './schemas.js';
export type {
  ArtifactActor,
  ArtifactCompareRequest,
  ArtifactCompareResponse,
  ArtifactConflictPolicy,
  ArtifactKindRegistration,
  ArtifactObservation,
  ArtifactQueryRequest,
  ArtifactQueryScope,
  ArtifactRef,
  ArtifactRelation,
  ArtifactRelationQueryTarget,
  ArtifactRelationTarget,
  ArtifactRepresentations,
  ArtifactRevision,
  ArtifactScope,
  ConfidenceBasis,
  ConfidenceLevel,
  ConfidenceMetadata,
  EvidenceRef,
  LocalRef,
  RelationTypeRegistration,
} from './schemas.js';
export { defineArtifactKind } from './kind-definition.js';
export type {
  AnyArtifactKindDefinition,
  ArtifactDataOf,
  ArtifactKindDefinition,
  ArtifactOf,
} from './kind-definition.js';
export { ArtifactNamespace, ArtifactSchemas, ArtifactSubjects } from './namespace.js';
export type {
  ArtifactCreatedPayload,
  ArtifactCreateRequest,
  ArtifactCreateResponse,
  ArtifactKindChangedPayload,
  ArtifactKindListRequest,
  ArtifactKindListResponse,
  ArtifactKindRegisterRequest,
  ArtifactKindRegisterResponse,
  ArtifactObservationAddedPayload,
  ArtifactQueryResponse,
  ArtifactRelationAddedPayload,
  ArtifactRelationTypeListRequest,
  ArtifactRelationTypeListResponse,
  ArtifactRelationTypeRegisterRequest,
  ArtifactRelationTypeRegisterResponse,
  ArtifactResolveRequest,
  ArtifactResolveResponse,
  ArtifactRevisedPayload,
  ArtifactReviseRequest,
  ArtifactReviseResponse,
  ArtifactStatusChangedPayload,
} from './namespace.js';
