import type {
  CacheStrategy,
  JsonValue,
  Message,
  MessageDeliveryMode,
  MessageOutcome,
  ResponseSchemaDescriptor,
  RequestCorrelationContext,
  SendMessageResultInnerResult,
  StructuredOutputValidation,
} from '@makaio/contracts';

/**
 * Result of a message operation.
 */
export type MessageResult = {
  result?: SendMessageResultInnerResult | null;
  error?: Error | string;
  outcome: MessageOutcome;
  /** Present when outcome='superseded': the messageId that replaced this one */
  supersededBy?: string;
  /** Present when outcome='merged': the messageId this was folded into */
  mergedInto?: string;
  /**
   * Structured-output validation result for this turn.
   * Present only when a {@link ResponseSchemaDescriptor} was active and validation ran.
   */
  structuredOutputValidation?: StructuredOutputValidation;
};

/**
 * Lifecycle states for a queued message.
 */
export type MessageState =
  | 'queued' // In queue, waiting for turn boundary
  | 'acknowledged' // SDK echoed message (isReplay received)
  | 'completed' // Result received for this message's turn
  | 'cancelled'; // Message was cancelled before submission

/**
 * Options for sending a message.
 */
export interface SendMessageOptions {
  /**
   * Custom identifier for message tracking (generated if not provided).
   */
  messageId?: string;

  /**
   * Controls delivery behavior.
   * @defaultValue 'enqueue'
   */
  deliveryMode?: MessageDeliveryMode;
}

/**
 * Options bag used when creating a message handle.
 *
 * Passed to {@link MessageHandle} via `AIAgentConnector.createMessageHandle`.
 */
export interface MessageHandleOptions {
  /** Optional stable message identifier; autogenerated when omitted. */
  messageId?: string;
  /** Optional delivery semantics for queue processing. */
  deliveryMode?: MessageDeliveryMode;
  /** Optional prior conversation messages to materialize for the turn. */
  messageHistory?: Message[];
  /** Optional per-turn metadata/context payload for prompt materialization. */
  turnContext?: Record<string, JsonValue>;
  /** Content-free transport context that must never be added to model input. */
  requestCorrelation?: RequestCorrelationContext;
  /** Caller-expressed caching intent for the injected history prefix. */
  cacheStrategy?: CacheStrategy;
  /**
   * Per-turn structured-output schema descriptor.
   * When set, the agent's structured-output manager validates the terminal
   * message against this schema before emitting completion events.
   */
  responseSchema?: ResponseSchemaDescriptor;
  /**
   * Whether this message handle was created for an internal retry turn.
   * When `true`, the `onMessageSent` callback is suppressed so no
   * `user_message.sent` event is emitted for the synthetic retry message.
   */
  internalRetry?: boolean;
}

/**
 * Processing state for agent orchestration.
 */
export type ProcessingState =
  | 'idle'
  | 'processing_started'
  | 'turn_started'
  | 'step_started'
  | 'step_finished'
  | 'turn_finished'
  | 'processing_finished'
  | 'active'
  | 'paused';
