import { defineConfig } from 'drizzle-kit';

// Invoked from this package's root by the `db:generate` scripts. The schema
// barrel is generated by the generate-schema step of @makaio/storage-migrations
// (the central migration runner), which aggregates every workspace package's
// declared Postgres schema files before drizzle-kit diffs them against the
// committed chain in ./drizzle-postgres.
export default defineConfig({
  schema: '../migrations/.generated/schema.postgres.ts',
  out: './drizzle-postgres',
  dialect: 'postgresql',
});
