/**
 * Adapter configuration factory interface.
 *
 * Defines the seam between agent-provided partial config and adapter-specific full config.
 * Each adapter implements this to:
 * 1. Apply default model if not provided
 * 2. Merge provider-specific configuration
 * 3. Validate and transform input
 * @typeParam TConfig - The full adapter-specific config type (extends BaseAgentConnectorConfig)
 * @typeParam TBus - The scoped bus type for this adapter
 */

import type { ScopedBus } from '@makaio/bus-core';
import type { AIReasoningLevel, ReasoningLevelMap } from '../types/ai-model.js';
import type { BaseAgentConnectorConfig } from '../agent/types.js';
import type { TimeoutConfig } from '@makaio/utils';
import type { McpRuntimeSessionContext, McpSessionContext, ProviderContext } from '@makaio/contracts';
import type { LedgerSessionContext, ISessionToolLedger } from '../agent/session-tool-ledger.js';

/**
 * Input provided by agent to the config factory.
 * Contains partial configuration - adapters provide defaults for missing required fields.
 *
 * Includes all runtime options from StartAgentRequest (allowedTools, disallowedTools, etc.)
 * to ensure they flow through to the connector.
 */
export interface ConfigFactoryInput<TBus extends ScopedBus<string> = ScopedBus<string>> {
  /** Scoped bus for adapter-specific events */
  bus: TBus;
  /** Unique agent identifier (required - generated by AIAgent) */
  agentId: string;
  /** Adapter instance identifier (required - provided by AIAgent from adapter) */
  adapterId: string;
  /** Adapter type name (required - provided by AIAgent from adapter) */
  adapterName: string;
  /**
   * Unresolved provider context (credential refs, not plaintext).
   * Connectors resolve credentials locally via `resolveConnectorCredentials()`.
   */
  providerContext: ProviderContext;
  /** Provider's session ID for resuming existing conversations */
  adapterSessionId?: string;
  /** Makaio session ID for tool execution context and multi-session correlation */
  sessionId?: string;
  /** Previous adapter session ID for resume attempts (from recovery). */
  resumeAdapterSessionId?: string;
  /** Model to use - optional, adapters provide defaults */
  model?: string;
  /** Working directory for agent execution */
  cwd?: string;
  /** Environment variables to pass to agent execution */
  env?: Record<string, string>;
  /** Reasoning effort for supporting adapters */
  reasoningEffort?: AIReasoningLevel;
  /** Reasoning levels supported by the resolved model, forwarded to the connector. */
  supportedReasoningLevels?: ReasoningLevelMap;
  /** Error handler for connector errors */
  errorHandler?: (error: Error, terminate: boolean) => void;

  // Runtime options from StartAgentRequest (flow through to connector)
  /** Allowed tool names (adapter-specific). Empty array = disable all tools. */
  allowedTools?: string[];
  /** Disallowed tool names (adapter-specific). Takes precedence over allowedTools. */
  disallowedTools?: string[];
  /** Directory restrictions for file-system tool execution. */
  allowedDirectories?: string[];

  /** Provider-specific configuration (non-credential settings). Adapters merge with defaults. */
  providerConfig?: Record<string, unknown>;

  runtimeTimeouts?: TimeoutConfig;

  /** Client identifier for the application this adapter belongs to (e.g., 'claude-code', 'gemini'). */
  clientId?: string;

  /** Client profile name for session-scoped config isolation. */
  clientProfileName?: string;

  /** Harness identifier used to resolve per-agent tool governance. */
  harnessId?: string;

  /**
   * Resolved MCP session context including upstream server configs.
   * When present, native-passthrough adapters use `servers` to configure SDK MCP connections.
   */
  mcpSessionContext?: LedgerSessionContext | McpRuntimeSessionContext | McpSessionContext;
  /**
   * Session-scoped MCP tool ledger.
   * Passed through unchanged so connectors can track injection and mcp_call usage.
   */
  toolLedger?: ISessionToolLedger;
}

/**
 * Interface for adapter-specific configuration factories.
 *
 * Transforms partial ConfigFactoryInput into full adapter-specific config.
 * The key responsibility is applying adapter defaults (especially model).
 * @example
 * ```typescript
 * const OpenAIConfigFactory: IAdapterConfigFactory<OpenAINodeAgentConfig> = {
 *   getConfig: async (input) => ({
 *     ...input,
 *     model: input.model ?? 'gpt-4o',
 *     providerConfig: { debugMode: true },
 *   }),
 * };
 * ```
 */
export interface IAdapterConfigFactory<
  TConfig extends BaseAgentConnectorConfig,
  TBus extends ScopedBus<string> = ScopedBus<string>,
> {
  getConfig(input: ConfigFactoryInput<TBus>): Promise<TConfig>;
}
