import { z } from 'zod';

/**
 * Schema for completion tokens breakdown.
 * Matches OpenAI CompletionUsage.CompletionTokensDetails structure.
 */
const CompletionTokensDetailsSchema = z.object({
  /** Tokens from predicted outputs that appeared in completion */
  accepted_prediction_tokens: z.number().optional(),
  /** Audio tokens generated by the model */
  audio_tokens: z.number().optional(),
  /** Tokens generated for reasoning */
  reasoning_tokens: z.number().optional(),
  /** Tokens from predicted outputs that did not appear */
  rejected_prediction_tokens: z.number().optional(),
});

/**
 * Schema for prompt tokens breakdown.
 * Matches OpenAI CompletionUsage.PromptTokensDetails structure.
 */
const PromptTokensDetailsSchema = z.object({
  /** Audio tokens in the prompt */
  audio_tokens: z.number().optional(),
  /** Tokens read from cache */
  cached_tokens: z.number().optional(),
});

/**
 * Schema for token usage event.
 * Based on OpenAI CompletionUsage structure with additional cache fields.
 * @see https://platform.openai.com/docs/api-reference/chat/object#chat/object-usage
 */
export const UsageEventSchema = z.object({
  eventType: z.literal('usage'),
  /** Number of tokens in the prompt */
  prompt_tokens: z.number(),
  /** Number of tokens in the generated completion */
  completion_tokens: z.number(),
  /** Total tokens used (prompt + completion) */
  total_tokens: z.number(),
  /** Breakdown of prompt tokens */
  prompt_tokens_details: PromptTokensDetailsSchema.optional(),
  /** Breakdown of completion tokens */
  completion_tokens_details: CompletionTokensDetailsSchema.optional(),
});

export type UsageEvent = z.infer<typeof UsageEventSchema>;
