import fs from 'node:fs';
import path from 'node:path';
import type { AstroIntegration } from 'astro';

const FRAMEWORK_ROOT = path.resolve(import.meta.dirname, '..', '..', '..');
const SOURCE_DIR = path.resolve(FRAMEWORK_ROOT, 'docs/subjects');
const OUTPUT_DIR = path.resolve(import.meta.dirname, '..', 'src/content/docs/reference/subjects');

/** Options for {@link generateBusSubjects}. */
export interface GenerateBusSubjectsOptions {
  /** Source directory containing generated Markdown docs. */
  readonly sourceDir?: string;
  /** Destination directory inside Starlight's content tree. */
  readonly outputDir?: string;
}

/**
 * Recursively copies Markdown files from a source directory to a destination.
 * @param src - Source directory containing committed bus subject docs.
 * @param dest - Destination directory inside Starlight's content tree.
 */
export function copyMarkdownTree(src: string, dest: string): void {
  fs.mkdirSync(dest, { recursive: true });

  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    const srcPath = path.join(src, entry.name);
    const destPath = path.join(dest, entry.name);

    if (entry.isDirectory()) {
      if (entry.name === 'data') continue;
      fs.mkdirSync(destPath, { recursive: true });
      copyMarkdownTree(srcPath, destPath);
    } else if (entry.isFile() && entry.name.endsWith('.md')) {
      fs.copyFileSync(srcPath, destPath);
    }
  }
}

/**
 * Creates an Astro integration that copies committed bus subject docs into
 * Starlight's content tree before content loading.
 *
 * The committed docs at `docs/subjects/` are generated by `yarn docs:bus` and
 * already contain Starlight frontmatter and framework GitHub source links
 * selected by the generator. This integration simply mirrors them into the
 * content directory so
 * Starlight's `autogenerate` sidebar can discover them by file path.
 * @param options - Optional source and destination overrides for tests or alternate hosts.
 * @returns Astro integration for bus subject reference pages.
 */
export function generateBusSubjects(options: GenerateBusSubjectsOptions = {}): AstroIntegration {
  const sourceDir = options.sourceDir ?? SOURCE_DIR;
  const outputDir = options.outputDir ?? OUTPUT_DIR;

  return {
    name: 'generate-bus-subjects',
    hooks: {
      'astro:config:setup': () => {
        if (!fs.existsSync(sourceDir)) {
          throw new Error(
            `Bus subject docs not found at ${sourceDir}. Run 'yarn docs:bus' from the framework root first.`,
          );
        }

        fs.rmSync(outputDir, { recursive: true, force: true });
        fs.mkdirSync(outputDir, { recursive: true });
        copyMarkdownTree(sourceDir, outputDir);
      },
    },
  };
}
